# Generated by Django 5.0.2 on 2024-05-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo',
            new_name='app',
        ),
    ]
